variables:
  TURBO_TELEMETRY_DISABLED: 1

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_REF_PROTECTED == "true"


stages:
  - prepare
  - test
  - openapi
  - docker


include:
  - project: "eiswind/mise-build-image"
    ref: "main"
    file: "ci-templates/build-ci-image.yml"

image:
  name: $CI_REGISTRY_IMAGE/ci-build
  docker:
    user: ubuntu

test:
  stage: test
  script:
    - "pnpm config set store-dir $CI_PROJECT_DIR/.pnpm-store"
    - "pnpm install --frozen-lockfile"
    - "pnpm run lint"
    - "pnpm run test"
    - "pnpm run build"
    - "pnpm run knip"
  artifacts:
    paths:
      - '__openapi__'
      - 'dist'
      - 'drizzle'
      - 'node_modules'

openapi:
  stage: openapi
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: manual
      allow_failure: true
  needs:
    - test
  script:
    - "pnpm config set store-dir $CI_PROJECT_DIR/.pnpm-store"
    - "pnpm install --frozen-lockfile"
    - "pnpm run generate:openapi"
    - "pnpm install --lockfile-only"
    - 'pnpm --filter "@eiswind-training-packages/bulletin-api-**" run build'
  artifacts:
    paths:
      - '__openapi__'

publish:
  stage: openapi
  rules:
    - when: manual
      allow_failure: true
  needs:
    - openapi
  script:
    - "pnpm config set //$CI_SERVER_HOST/api/v4/projects/170/packages/npm/:_authToken=$CI_JOB_TOKEN"
    - "cd $CI_PROJECT_DIR/__openapi__/angular-client/dist"
    - "pnpm publish --tag=latest"
    - "cd $CI_PROJECT_DIR/__openapi__/fetch-client"
    - "pnpm publish -tag=latest"




docker-image:
  cache: [ ]
  stage: docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: manual
      allow_failure: true
  needs:
    - test
  image:
    name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:cli
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:dind
      alias: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/training/bulletin-backend/bulletin-test-backend-elysia:latest .
    - docker push $CI_REGISTRY/training/bulletin-backend/bulletin-test-backend-elysia:latest
